adding in additional use cases for errors
ethereum/keymanager-APIs pull request #10
Opened 2021-11-23 20:50 UTC by james-prysm

adding in usecases for strange behavior

2021-11-23 22:46 UTC, rolfyone commented on use-cases/README.md
> + - Slashing Protection on keys that are not imported will still be imported.
i mean technically you could import slashing protection thats completely unrelated to the entire set...

2021-11-23 22:49 UTC, rolfyone commented on use-cases/README.md
> + - Duplicate Keystores on import will not be imported and return with  `duplicate` status.
more specifically if a key is being imported and that key is already active in the validator it's duplicate....
so if the first key is new, it gets success; second key is the same, then it gets duplicate (the first import in the batch added it)
or also if there is 1 key and it happens to be active already in the target, then it would be a duplicate...
the response is still a 200 overall, and the status of that individual import is duplicate...

2021-11-23 22:50 UTC, rolfyone commented on use-cases/README.md
> + - Slashing Protection will only export for keys with `deleted` status.
need to export deleted and not_active, to cover the use case where a subsequent call to delete can be used to get slashing data again...

2021-11-23 22:54 UTC, rolfyone commented on use-cases/README.md
> + - `DELETE` API can be called with an empty array to only export slashing protection data.
are you saying to export all slashing protection data? 
My take on it is I don't want to ever export slashing protection data for an active validator...

You can request data and i'll give it back for deleted or not active validators, but the active validator data I don't think we should be passing around.

My read was that you'd have the pubkey you want data on that's not active, and it'd return that.

2021-11-24 00:01 UTC, michaelsproul requested changes

2021-11-24 00:01 UTC, michaelsproul commented on use-cases/README.md
> + - `POST` API is not transactional on bulk import.
```suggestion
 - `POST` API is not required to be transactional on bulk import.
```

An implementation _may_ be transactional if it wishes, but I doubt any existing impls will be.

2021-11-24 00:28 UTC, rolfyone commented on use-cases/README.md
> + - If there is more than 1 password but less than the amount of total keystores then the `POST` API will return an error response
Ok that makes sense, probably where my understanding came from

2021-11-24 19:33 UTC, james-prysm commented on use-cases/README.md
> + - `DELETE` API can be called with an empty array to only export slashing protection data.
I thought it would return the full set of slashing protection data on all deleted status keys, is that not the case? or is it on all no_active keys? and that when a key is deleted it is changed to not active status instead of deleted status? 🤔  I think I am still misunderstanding something.

2021-11-24 19:33 UTC, james-prysm commented on use-cases/README.md
> + - If there is more than 1 password but less than the amount of total keystores then the `POST` API will return an error response
ok that's fair will update this.

2021-11-24 19:35 UTC, james-prysm commented on use-cases/README.md
> + - Slashing Protection on keys that are not imported will still be imported.
added a note to clairify

2021-11-24 21:10 UTC, james-prysm commented on use-cases/README.md
> + - `DELETE` API can be called with an empty array to only export slashing protection data.
paul clarified with this example

 a, a, b, c in request, and they're a: deleted, a: not_active, b: not_found, c:deleted, then i get slashing data for a,c

will update accordingly

2021-11-24 21:32 UTC, james-prysm commented on use-cases/README.md
> + - Slashing Protection will only export for keys with `deleted` status.
updated

2021-11-26 20:32 UTC, rolfyone commented on use-cases/README.md
> + - `DELETE` API will not return an error response on failed key deletions but instead return the public key with `error` status
i think these bits are better covered by the flows...

2021-11-30 00:53 UTC, michaelsproul commented on use-cases/README.md
> + - `DELETE` API can be called with an empty array to only export slashing protection data.
I think this line still needs to be deleted

2021-11-30 21:45 UTC, michaelsproul approved these changes
LGTM!

2021-11-30 21:46 UTC, merged