Add validator voluntary exit endpoint
ethereum/keymanager-APIs pull request #58
Opened 2023-03-24 04:25 UTC by jimmygchen

Addresses #57.

I've incorporated inputs from the discussions in the above issue and the R&D #api channel.

2023-03-24 04:26 UTC, jimmygchen commented
Converting back to draft as I just realised that I need to update the `flows` and `use-cases` docs.

2023-03-24 04:32 UTC, jimmygchen commented
I've just went through the docs and not sure if extra info is need for this endpoint - I think the description and spec of the endpoint seems adequate, but please let me know otherwise!

2023-03-25 16:43 UTC, rkapka requested changes
Copying from Discord:
> I don't really see the purpose of the confirmation query parameter. In CLI apps we usually issue a warning after the user initiates an operation, and confirming is a second step. The warning is there to allow the user to back out from the operation. The semantics of an API query parameter are different. We only have a single step, so you either go through with the operation when including the query param or you don't when not including it - the param doesn't add any value. I don't ever see a reason for anyone to invoke the endpoint without the query parameter because it will just fail (which, again, doesn't work that way in a CLI app). In my opinion it is redundant.

2023-03-28 01:33 UTC, dapplion commented
Agree with the reasoning above, I would drop confirm param too

2023-03-28 01:36 UTC, jimmygchen commented
> Agree with the reasoning above, I would drop confirm param too

Thanks @dapplion - there's some discussions on this topic in the #api channel on R&D, and it looks like the consensus so far is to drop the query param. The alternative proposal is to change the API, so that it returns a `SignedVoluntaryObject` and let the user send it to the Beacon API, making it a two step process. This would prevent a simple curl from triggering an irreversible operation.

If there's no strong objections I'll update this PR shortly.

2023-03-28 03:10 UTC, jimmygchen commented
@dapplion and Adrian also raised that web3signer implements keymanager API but can't fetch the current epoch like VC does, so we'll have to make epoch a mandatory param.

2023-03-28 05:24 UTC, jimmygchen commented
Updated the endpoint based on discussion in api channel:
- Return `SignedVoluntaryExit` object in response
- Remove `confirm` query parameter
- Make `epoch` query parameter mandary

2023-03-29 00:36 UTC, jimmygchen commented
Discussion from Discord - given that remote signers already supports signing voluntary exits, and does not implement the full keymanger API, this endpoint doesn't seem necessary for remote signer.

I've made the `epoch` query parameter optional, as validator client has knowledge of the current epoch and can set this as default. Also updated the tag description to explicitly mention sections that are "Validator Client only" - Fee recipient, Gas Limit & Voluntary exits.

2023-03-29 11:42 UTC, rolfyone commented on keymanager-oapi.yaml
> +    description: Validator client only - set of endpoints for voluntary exits.
I think exits should be fine from anything that can implement this endpoint - eg. web3signer would be appropriate, equally BN would be appropriate...

2023-03-29 11:43 UTC, rolfyone commented on keymanager-oapi.yaml
> +    description: Validator client only - set of endpoints for management of fee recipient. Requires access to a beacon node.
Given we're not playing with anything in this endpoint, I'd prefer this was a separate PR, as well as gas limit change - they're not really related to the exit endpoint at all...

2023-03-29 20:10 UTC, rolfyone commented on apis/voluntary_exit.yaml
> +          $ref: '../keymanager-oapi.yaml#/components/schemas/Uint64'
I wonder if we should make `validator_index` an optional query parameter...

I know it's technically redundant but if we had it then tools like web3signer might be in with a shot of implementing this endpoint... and it's in the actual signed exit.... Obviously if it didn't match up and the server could see that, it could be a 400 pretty easily...

2023-03-29 23:09 UTC, jimmygchen commented on apis/voluntary_exit.yaml
> +          $ref: '../keymanager-oapi.yaml#/components/schemas/Uint64'
I'm not sure how important this endpoint would be for Web3Signer, since it already has a [sign endpoint](https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Signing/operation/ETH2_SIGN) for `VOLUNTARY_EXIT` that accepts `epoch` and `validator_index`, however it also requires `fork_info` and `signing_root` as well, so I'm not sure if this endpoint would work for them even if `validator_index` is provided? Be great if someone could confirm?

For Lighthouse, this may make it a bit more complicated than it needs to be ,as validators are indexed by public keys, so I would prefer to avoid extra scenarios to handle unless it's really necessary, but I could be easily convinced if this endpoint adds value to external signers.

2023-03-29 23:13 UTC, rolfyone commented on apis/voluntary_exit.yaml
> +          $ref: '../keymanager-oapi.yaml#/components/schemas/Uint64'
yep all good, ignore this :)

2023-03-29 23:13 UTC, rolfyone approved these changes
LGTM

2023-03-29 23:44 UTC, dapplion approved these changes

2023-03-30 01:29 UTC, merged